### PR TITLE
Bump upper bound on vector

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
Abhinav Gupta <notifications@github.com> writes:

> abhinav approved this pull request.
>
> Will merge and release once the build passes
>
Thanks!

**Comment by abhinav** [comment]
Looks like the build is failing because of https://github.com/haskell/cabal/issues/2653

**Comment by abhinav** [comment]
Testing a fix https://github.com/abhinav/pinch/pull/12

**Comment by abhinav** [comment]
0.3.0.2 released with this change

**Pull request merged**
